### ISSUE TITLE
Windows  32/64 bit binaries without option bmi2

### ISSUE THREAD

**Issue by yellow-panther** [hiblom/haddock#1]
Hello hiblom,
can you build Windows 32/64 bit binaries on your website with a sub-directory e.g. /releases please?
Unfortunately I am not a programmer - bmi2 cf. https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets
Regards,

**Comment by hiblom** [comment]
Hello yellow-panther,
This project is not yet ready for release. When it is, i will make binaries.
Regards, Hans
